### ISSUE TITLE
v1.0.4 not available on bower

### ISSUE THREAD

**Issue by michaelkrone** [hiebj/ng-focus-if#19]
Version 1.0.4 is only available on npm.
We need this version, because 1.0.2 breaks if minified by uglify, could you please publish the latest version to bower?

**Comment by rllola** [comment]
+1

**Comment by hiebj** [comment]
sorry guys - I did the version bump and created the tag for the fix, and completely forgot to `git push --tags`. I pushed up, so `bower install` should pull v1.0.4 now.
