### ISSUE TITLE
Select text on Focus

### ISSUE THREAD

**Issue by bradyclifford** [hiebj/ng-focus-if#2]
Would it be possible to add an additional feature to this directive:

-When autofocus attribute is set on an input tag, it selects all of its text?
-Ability to turn this additional feature on and off per element or globally

**Comment by hiebj** [comment]
https://github.com/hiebj/ng-autofocus/commit/685a7047ff91d10e23812c1b6a73fe16bc3e582f

<input autoselect value="something" />

Can also be used with autofocus if you want. Technically they are separate directives. `autoselect` will highlight all the text on a field any time it is focused, regardless whether it was triggered by autofocus.

Does this serve your use case? I realize this implementation means that all text will be selected anytime the field is focused under any conditions, not just when focus is triggered by autofocus. I figured that autoselect is kind of a separate thing that you might want to do even without autofocus.

**Comment by hiebj** [comment]
https://github.com/hiebj/ng-autoselect

Try that. At first I added the functionality to ng-autofocus, but they are really separate directives. It should work great using both:

```
<input autoselect autofocus />
```

http://jsfiddle.net/hiebj/54cz9c6v/
Note that `autofocus` doesn't work in JSFiddle, for some reason it has trouble with the `iframe`.

I'll publish the ng-autoselect package to NPM as soon as I have a chance to write up a README.

**Comment by bradyclifford** [comment]
I will give it a try.  Thanks for the quick feedback.
