### ISSUE TITLE
autofocus attribute conflicks with the native autofocus attribute.

### ISSUE THREAD

**Issue by bradyclifford** [hiebj/ng-focus-if#3]
If you use autofocus, it will set the focus for that element twice. First by the directive and than by the browser.

If you use autofocus="condition" it will compete with the browser's native autofocus.

We had to use data-autofocus to mitigate this issue.  Is there another way?

**Comment by hiebj** [comment]
I hadn't experienced this issue before, although I can see how it might be a problem. The only thing I can think of is changing the name of the directive, or else writing some code to reconcile it with the native attribute (e.g. some kind of `preventDefault` situation, although that seems like overkill).

I'd be happy to change the name except that I use the directive quite a bit in my own code and would have to push the change everywhere, as would anyone else using it. I could create an alias.

I'll think about it and see if I can come up with something clever. If you could post a JSFiddle or Plunkr that demonstrates the specific problem you're having, I might be able to address it faster; I'm trying to finish a release at work, so I won't have a lot of time to look into this for a few days.

**Comment by hiebj** [comment]
If `data-autofocus` works effectively, it may make sense to just use that, and document it officially as a solution. Otherwise we could create a similar alias that doesn't require you to use `autofocus` itself, like `auto-focus`. But there may be a code solution as well that allows them to play nice. Personally, I'd just go with `data-autofocus` for now. I'll look into it though.

**Comment by TomBecker-BD** [comment]
Same issue. It doesn't stop the directive from working, but I was getting a syntax warning in the HTML editor. Using `data-autofocus` gets rid of the warning and the directive still works.

**Comment by hiebj** [comment]
Ok, I'm going to go ahead and address this in the next day or so. I'm just going to add an alias, trying to decide on the name. What do you guys like? The ideas I have are `auto-focus`, `focusif` and simply `focus`. If I use `focus` or `focusif`, I may also add an alias for `focus-delay` for consistency.

If I don't get a quick response I'll probably go with `focus`.

**Comment by TomBecker-BD** [comment]
I am not having any problems with `data-autofocus`. Unless there is some issue I am not aware of, I would be happy if it were documented as the official solution. 

If you are going to change the name, I think `auto-focus` and `focus` are too close to existing names `autofocus` and `ng-focus`. The clearest would be `focus-if`. 

By the way, thank you for creating a clean, simple directive that does just what we needed.

**Comment by bradyclifford** [comment]
The problem with making an alias instead of renaming the directive is in some cases, we want to use the native autofocus attribute.  The native autofocus attribute is able to set focus after an animation occurs, like setting the focus on a button withing a modal when it is animated and enters the screen.  When using your directive, data-autofocus, I have to set a delay on the focus for it to work.

**Comment by hiebj** [comment]
Yeah, I had thought of that. I was sort of hoping it wouldn't be an issue. Not sure what to do about it at the moment, I'll have to give it some thought. I'd rather not screw it up for people who are currently using the directive.

If I rename it I'll have to issue a major release just for the name change. It's not unthinkable, I may end up doing just that. I'll have to chew on it a bit though.

**Comment by hiebj** [comment]
Brady, would it be possible for you to set up a fiddle or plunkr that demonstrates the problem? I may be able to simply fall back on default browser behavior when it's implemented. The Angular input directives, for instance, allow the browser to do its job in the cases where the browser is advanced enough. It is conceivable that I might be able to simply ignore an empty `autofocus` when the browser already has an implementation.

**Comment by bradyclifford** [comment]
Ya I will get something setup.

On Thu, May 21, 2015 at 10:02 AM, Jonathan Hieb notifications@github.com
wrote:

> Brady, would it be possible for you to set up a fiddle or plunkr that
> demonstrates the problem? I may be able to simply fall back on default
> browser behavior when it's implemented. The Angular input directives, for
> instance, allow the browser to do its job in the cases where it's advanced
> enough. It is conceivable that if I understand the mechanism, I might be
> able to simply ignore an empty autofocus when the browser already has an
> implementation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hiebj/ng-autofocus/issues/3#issuecomment-104332518.

## 

Até mais,

_Brady Clifford_
_brady@cliffsters.com_ brady@cliffsters.com

brady@cliffsters.com

**Comment by hiebj** [comment]
Brady -

Sorry it has taken me a while to get around to looking into this. I pushed a branch, [native-support](https://github.com/hiebj/ng-autofocus/tree/native-support). It should allow the browser-native implementation of `autofocus` to take over when:
 - the browser supports it, and
 - it is used without a specified value (watch expression) and without the `autofocus-delay` attribute

e.g. `<input autofocus>`.

I also added a unit test to demonstrate this.

Tell me if this change solves your problem and I'll pull it into the master branch and do a release.

**Comment by hiebj** [comment]
Ok I have rethought it and there's nothing for it but to rename the directive. I can prevent the directive from taking over when the browser supports autofocus, but I can't prevent the browser from taking over and interpreting the autofocus attribute, at least not cleanly.

I'm going to rename the directive `focus-if`. Unfortunately that means I'll have to rename the repository as it no longer really makes sense. That will also mean a rename to the NPM package.

The new repository and package name will be `ng-focus-if`. I will leave the old NPM packages up for legacy purposes but I am going to deprecate all versions of it and put a note at the top of the documentation that will redirect people to `ng-focus-if`.

**Comment by bradyclifford** [comment]
Ok. That should work.

On Tue, Jun 9, 2015 at 5:07 PM, Jonathan Hieb notifications@github.com
wrote:

> Ok I have rethought it and there's nothing for it but to rename the
> directive. I can prevent the directive from taking over when the browser
> supports autofocus, but I can't prevent the browser from taking over and
> interpreting the autofocus attribute, at least not cleanly.
> 
> I'm going to rename the directive autofocus-if. I would use focus-if
> except for the fact that I'd feel obliged to rename the repository, and I'd
> rather not have to publish a package with a different name in NPM. I might
> be talked into adding aliases for focus-if and focus-delay.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hiebj/ng-autofocus/issues/3#issuecomment-110529007.

## 

Até mais,

_Brady Clifford_
_brady@cliffsters.com_ brady@cliffsters.com

brady@cliffsters.com
