### ISSUE TITLE
scroll into focus

### ISSUE THREAD

**Issue by bradyclifford** [hiebj/ng-focus-if#4]
Would it be possible to add a scroll into focus ability to the auto-focus directive?  Or is there a separate directive that can piggyback on this?

**Comment by hiebj** [comment]
Interesting idea. I don't see why not. Although, in most of the browsers I've tested, the viewport will automatically scroll to a focused element. Is that not true in your case?

**Comment by bradyclifford** [comment]
It depends.  With the grids that we are using, like UI-grid, we aren't seeing it scroll on focus.

**Comment by bradyclifford** [comment]
It isn't a big deal.  We can find alternatives.

**Comment by hiebj** [comment]
I am working on this one. Should be easy enough using `Element.scrollIntoView()`, possibly recursively if the `offsetParent` is not the main viewport.

It gets ugly if there are too many layers of scrollable content though. I can't really think of a reasonable use case to have a scrollable view within a scrollable view within a scrollable view. It seems like it may be reasonable to just use `scrollIntoView()` on the element itself. I'll chew on it for a bit though.

**Comment by bradyclifford** [comment]
Great.

On Tue, Jun 9, 2015 at 6:15 PM, Jonathan Hieb notifications@github.com
wrote:

> I am working on this one. Should be easy enough using
> Element.scrollIntoView (to get your grid to scroll) and possibly offsetTop
> to scroll the main viewport if the element is still not on screen (e.g. the
> grid itself is not currently on screen).
> 
> It gets ugly if there are too many layers of scrollable content though. I
> can't really think of a reasonable use case to have a scrollable view
> within a scrollable view within a scrollable view, but I'll chew on it for
> a bit.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hiebj/ng-focus-if/issues/4#issuecomment-110540535.

## 

Até mais,

_Brady Clifford_
_brady@cliffsters.com_ brady@cliffsters.com

brady@cliffsters.com

**Comment by hiebj** [comment]
I'm gonna close this. I've been meaning to take a second look for a long time but haven't really had a chance or seen it reproduced in my own experience. I'm thinking another directive targeted for the specific use case is probably appropriate.
